openapi: 3.0.0
info:
  title: Actualizar Cliente
  description: Endpoint para actualizar la información de un cliente existente
  version: 1.0.0
paths:
  /api/customers/{id}:
    put:
      tags:
        - Clientes
      summary: Actualizar cliente por ID
      description: Actualiza la información de un cliente existente identificado por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre del cliente
                email:
                  type: string
                  format: email
                  description: Correo electrónico del cliente
                telephone:
                  type: string
                  description: Número de teléfono (máximo 9 dígitos)
                  maxLength: 9
                identity_document_type_id:
                  type: string
                  description: Tipo de documento de identidad
                number:
                  type: string
                  description: Número de documento
                department_id:
                  type: string
                  description: ID del departamento
                province_id:
                  type: string
                  description: ID de la provincia
                district_id:
                  type: string
                  description: ID del distrito
                address:
                  type: string
                  description: Dirección del cliente
              required:
                - name
                - identity_document_type_id
                - number
      responses:
        '200':
          description: Cliente actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID del cliente
                      name:
                        type: string
                        description: Nombre del cliente
                      number:
                        type: string
                        description: Número de documento
                      telephone:
                        type: string
                        description: Teléfono
                      email:
                        type: string
                        description: Correo electrónico
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Cliente no encontrado"
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error en los datos proporcionados"
                  errors:
                    type: object
                    description: Detalle de errores de validación
