openapi: 3.0.0
info:
  title: API de Clientes
  version: 1.0.0
  description: API para gestionar clientes

paths:
  /api/customers/filter:
    get:
      tags:
        - Clientes
      summary: Listar Clientes por Estado
      description: Obtiene una lista de clientes filtrada por su estado
      operationId: listarClientesPorEstado
      parameters:
        - in: query
          name: status
          required: true
          description: Estado del cliente
          schema:
            type: string
            enum: [active, inactive]
            example: active
      responses:
        '200':
          description: Lista de clientes obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Clientes encontrados"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID del cliente
                          example: 55
                        description:
                          type: string
                          description: Descripción completa del cliente
                          example: "72346556 - Pedro Diaz"
                        name:
                          type: string
                          description: Nombre del cliente
                          example: "Pedro Diaz"
                        number:
                          type: string
                          description: Número de documento
                          example: "72346556"
                        identity_document_type_id:
                          type: string
                          description: Tipo de documento de identidad
                          example: "1"
                        address:
                          type: string
                          description: Dirección del cliente
                          example: "Urb Sesquicentenario Vipol Callao"
                        email:
                          type: string
                          description: Correo electrónico
                          example: "cliente@email.com"
                        telephone:
                          type: string
                          description: Número de teléfono
                          example: "954533737"
                        status:
                          type: string
                          description: Estado del cliente
                          example: "active"
                        created_at:
                          type: string
                          description: Fecha de creación
                          example: "2023-08-17 10:30:00"
        '400':
          description: Parámetro de estado inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "El estado proporcionado no es válido"
        '404':
          description: No se encontraron clientes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "No se encontraron clientes con el estado especificado"
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
