openapi: 3.0.0
info:
  title: Obtener Información de Cliente
  description: Endpoint para obtener información detallada de un cliente incluyendo documentos, notas de venta, totales y deuda pendiente
  version: 1.0.0
paths:
  /api/customers/info/{id}:
    get:
      tags:
        - Clientes
      summary: Obtener información detallada de un cliente
      description: Obtiene información completa de un cliente incluyendo documentos emitidos, notas de venta, totales consumidos, pagos realizados y deuda pendiente
      parameters:
        - name: id
          in: path
          required: true
          description: ID del cliente del cual obtener la información
          schema:
            type: integer
            example: 55
      responses:
        '200':
          description: Información del cliente obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer:
                    type: object
                    description: Información básica del cliente
                    properties:
                      id:
                        type: integer
                        description: ID del cliente
                        example: 55
                      type:
                        type: string
                        description: Tipo de persona
                        example: "customers"
                      number:
                        type: string
                        description: Número de documento
                        example: "72346556"
                      name:
                        type: string
                        description: Nombre del cliente
                        example: "Pedro Diaz"
                      email:
                        type: string
                        nullable: true
                        description: Correo electrónico del cliente
                        example: "pedro@example.com"
                      telephone:
                        type: string
                        nullable: true
                        description: Teléfono del cliente
                        example: "954533737"
                      address:
                        type: string
                        nullable: true
                        description: Dirección del cliente
                        example: "Urb Sesquicentenario Vipol Callao"
                      identity_document_type:
                        type: object
                        nullable: true
                        description: Tipo de documento de identidad
                        properties:
                          description:
                            type: string
                            example: "DNI"
                  documents_count:
                    type: integer
                    description: Cantidad total de documentos del cliente (facturas, boletas y notas de venta)
                    example: 15
                  total_consumed:
                    type: string
                    description: Total consumido por el cliente (formateado)
                    example: "1,250.50"
                  total_paid:
                    type: string
                    description: Total pagado por el cliente (formateado)
                    example: "1,000.00"
                  pending_debt:
                    type: string
                    description: Deuda pendiente del cliente (formateado)
                    example: "250.50"
                  documents:
                    type: array
                    description: Lista de documentos del cliente (facturas y boletas)
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 123
                        series:
                          type: string
                          example: "F001"
                        number:
                          type: string
                          example: "00000001"
                        date_of_issue:
                          type: string
                          format: date
                          example: "2023-12-01"
                        total:
                          type: number
                          format: float
                          example: 150.50
                        document_type_id:
                          type: string
                          example: "01"
                  sale_notes:
                    type: array
                    description: Lista de notas de venta del cliente
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 456
                        series:
                          type: string
                          example: "NV01"
                        number:
                          type: string
                          example: "00000001"
                        date_of_issue:
                          type: string
                          format: date
                          example: "2023-12-01"
                        total:
                          type: number
                          format: float
                          example: 75.25
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Cliente no encontrado"
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Token inválido o expirado"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
